<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>se2_grid_core</name>
  <version>0.1.0</version>
  <description>Universal SE(2) grid library to manage two-dimensional grid maps with multiple data layers. Ported from ZJU-FAST-Lab/seb_naver.</description>
  <maintainer email="xulon666@gmail.com">Long Xu</maintainer>
  <license>BSD</license>
  <url type="website">https://github.com/ZJU-FAST-Lab/uneven_mapping</url>
  <author email="xulon666@gmail.com">Long Xu</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>eigen</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
